[server]
port = 80


[mysql]
address = "127.0.0.1:3306"
userName = "root"
password = "123456"
dbName = "jwt_enhance"
# 连接可复用的最大时间,分钟
connMaxLifeTime = 30
# 空闲连接池中连接的最大数量
maxIdleConn = 30
# 打开数据库连接的最大数量
maxOpenConn = 200
# 连接超时时间,秒
connMaxWaitTime = "20s"

